// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ShopImport } from './routes/shop'
import { Route as IndexImport } from './routes/index'
import { Route as ShopIndexImport } from './routes/shop/index'
import { Route as ShopProductIdImport } from './routes/shop/$productId'

// Create/Update Routes

const ShopRoute = ShopImport.update({
  path: '/shop',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ShopIndexRoute = ShopIndexImport.update({
  path: '/',
  getParentRoute: () => ShopRoute,
} as any).lazy(() => import('./routes/shop/index.lazy').then((d) => d.Route))

const ShopProductIdRoute = ShopProductIdImport.update({
  path: '/$productId',
  getParentRoute: () => ShopRoute,
} as any).lazy(() =>
  import('./routes/shop/$productId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/shop': {
      preLoaderRoute: typeof ShopImport
      parentRoute: typeof rootRoute
    }
    '/shop/$productId': {
      preLoaderRoute: typeof ShopProductIdImport
      parentRoute: typeof ShopImport
    }
    '/shop/': {
      preLoaderRoute: typeof ShopIndexImport
      parentRoute: typeof ShopImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ShopRoute.addChildren([ShopProductIdRoute, ShopIndexRoute]),
])
